package com.example.hello_selenium_java;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.opera.OperaOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.*;

public class SearchTestOpera {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void searchdevops() throws MalformedURLException {

        OperaOptions operaxOptions = new OperaOptions();
        driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444"), operaxOptions);

        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(904, 893));
        driver.switchTo().frame(0);
        driver.findElement(By.cssSelector("#introAgreeButton .RveJvd")).click();
        driver.switchTo().defaultContent();
        //driver.findElement(By.name("q")).click();
        WebElement we = new WebDriverWait(driver, 10)
                .until(ExpectedConditions.elementToBeClickable(By.name("q")));
        we.click();
        driver.findElement(By.name("q")).sendKeys("devops");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    }

}
