// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('imb-wandavision', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('imb-wandavision', async function() {
    await driver.get("https://www.imdb.com/")
    await driver.manage().window().setRect(1169, 691)
    await driver.findElement(By.id("suggestion-search")).click()
    await driver.findElement(By.id("suggestion-search")).sendKeys("wandavision")
    await driver.findElement(By.id("suggestion-search")).sendKeys(Key.ENTER)
  })
})
