// Generated by Selenium IDE
const { Builder, By, Key, until, Capabilities } = require('selenium-webdriver')
const assert = require('assert')

describe('imb-wandavision', function() {
  this.timeout(30000)
  let driver
  let vars
  var capabilities = new Capabilities().setBrowserName("chrome");
  beforeEach(async function() {
    //Se lanza desde el navegador firefox
    //driver = await new Builder().forBrowser('firefox').build()
    //Se lanza desde un navegador elegido por el grid
    driver = await new Builder()
        .usingServer("http://localhost:4444/wd/hub")
	.withCapabilities(capabilities)
        .build();
    vars = {}
  })

  afterEach(async function() {
    await driver.quit();
  })

  it('imb-wandavision', async function() {
    await driver.get("https://www.imdb.com/")
    await driver.manage().window().setRect(1169, 691)
    //await driver.findElement(By.id("suggestion-search")).click()
    //await driver.findElement(By.id("suggestion-search")).sendKeys("wandavision")
    //await driver.findElement(By.id("suggestion-search")).sendKeys(Key.ENTER)

    //Ejecutar con Wait
    await driver.wait(until.elementLocated(By.id('suggestion-search'))).click();
    await driver.switchTo().defaultContent();
    await driver.findElement(By.id("suggestion-search")).sendKeys('wandavision',Key.RETURN);
   })

})
