// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('search-devops', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('search-devops', async function() {
    await driver.get("https://www.google.com/")
    await driver.manage().window().setRect(904, 893)
    await driver.switchTo().frame(0)
    //Selenium-IDE
    //await driver.findElement(By.css("#introAgreeButton .RveJvd")).click()
    //await driver.switchTo().defaultContent()
    //await driver.findElement(By.name("q")).click()
    //await driver.findElement(By.name("q")).sendKeys("devops")
    //await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    
   //Script con wait
   await driver.wait(until.elementLocated(By.id('introAgreeButton'))).click();

   await driver.switchTo().defaultContent();
   await driver.findElement(By.name('q')).sendKeys('devops',Key.RETURN);
  })
})
